kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nsw-clusteradmin
subjects:
  - kind: ServiceAccount
    name: nsw  # awx is the default value.
    namespace: kube-system # default is tower
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin