kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: crd-clusteradmin
subjects:
  - kind: ServiceAccount
    name: crdaccount
    namespace: kube-system # default is tower
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin